### ISSUE TITLE
<Leader><Leader> alternative? 

### ISSUE THREAD

**Issue by arkan** [heetch/neovim-config#9]
I'm not a fan of this prefix.  Do you feel confortable with it @jhchabran?

**Comment by jhchabran** [comment]
I do, I find it more natural that `SPC m` that we previously used and I like the idea that `SPC` is for global stuff while `SPC SPC` is for language specifics. It's also very accessible and easy to remember, like `SPC SPC i` to show information about a variable in our Go code.

That being said the idea there is to have a common config for pair sessions, so if you're not comfortable with it, `SPC SPC` defeats the initial purpose. 

- What's bothering you exactly ? The need to press a key twice ?
- Do you have another prefix in mind ?

**Comment by arkan** [comment]
> What's bothering you exactly ? The need to press a key twice ?
Yes, so far with `<Leader><Leader>` I find this process to be cumbersome. But I should probably try to get use to it. I'll come back in a few days :) 

> Do you have another prefix in mind ?
Nope

**Comment by arkan** [comment]
I got used to it. So let's close this issue :)
